[package]
name = "swaytreesave"
version = "0.1.0"
edition = "2024"

[dependencies]
swayipc = "3.0.3"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
clap = { version = "4.5.37", features = ["derive"] }
xdg = "2.5.2"
humantime-serde = "1.1.1"

